### PR TITLE
Change packaging backend to use pyproject.toml with flit

### PR DESCRIPTION
**Pull request by mwtoews**
An alternative proposal to #66 is to use [flit](https://github.com/takluyver/flit) for packaging. Building is similar:
```bash
$ python3 -m pip install --upgrade build
...
$ python3 -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (flit_core >=2,<4)
* Getting dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (flit_core >=2,<4)
* Getting dependencies for wheel...
* Building wheel...
Successfully built affine-2.3.0.tar.gz and affine-2.3.0-py2.py3-none-any.whl
```
the wheel installs fine with Python 2.7, if that still matters.

### CODE REVIEW

**Comment by sgillies** [comment]
Hey @mwtoews I'm game for either this or #66. What are the pros and cons of each? Which is your favorite and why?

**Comment by mwtoews** [comment]
Not sure if I have a favourite yet, but leaning towards flit (see [why use flit](https://flit.readthedocs.io/en/latest/rationale.html) doc). It was recently adopted as a [PyPA Project](https://packaging.python.org/en/latest/key_projects/#pypa-projects), which boosts its credibility even further. I don't see any downsides.

**Comment by mwtoews** [comment]
This PR is updated to resolve conflicts. Also, I can re-add a [`setup.py` shim](https://stackoverflow.com/a/62983901/), if that's an expected file by someone.

**Comment by sgillies** [comment]
Done in 9fed202. Thanks @mwtoews !

**Pull request closed without merging**
